version: 2.1

jobs: # a basic unit of work in a run
  test: # your job name
    macos:
      xcode: 14.2.0 # indicate your selected version of Xcode
    steps: # a series of commands to run
      - checkout  # pull down code from your version control system.
    
      - run: |
          wget https://cran.r-project.org/bin/macosx/base/R-4.2.3.pkg
          sudo installer -pkg R-4.2.3.pkg -target /
          export R_HOME=`R RHOME`
          wget https://julialang-s3.julialang.org/bin/mac/x64/1.8/julia-1.8.5-mac64.tar.gz
          tar -xvzf julia-1.8.5-mac64.tar.gz
          cd  julia-1.8.5/bin
         # export PATH="$PATH:`pwd`"
          #export PYTHON=""
          #julia -e 'using Pkg; Pkg.add("RCall"); Pkg.add("PyCall"); Pkg.add("Conda");'
          #julia -e 'using Conda; Conda.pip_interop(true)'
          #julia -e 'using Conda; Conda.pip("install", "smlmvis")'
          #julia -e 'using Conda; Conda.pip("install", "meshio")'
          #julia -e 'using PyCall; pyimport("smlmvis")'
          #julia -e 'using Pkg; '
          #julia -e 'using Pkg; Pkg.add(url="https://github.com/bencardoen/SlurmMonitor.jl.git"); Pkg.add(url="https://github.com/bencardoen/SmlmTools.jl.git");'
          #julia -e 'using Pkg; Pkg.add(url="https://github.com/bencardoen/DataCurator.jl.git");' 
          #julia -e 'using Pkg; Pkg.build("DataCurator"); Pkg.test("DataCurator");'
         

  build: 
    macos:
      xcode: 14.2.0 # indicate your selected version of Xcode
    steps: 
      - checkout
      - run:
          # build our application
          name: Build Application
          command: echo "Hi"

          
workflows:
  test_build:
    jobs:
      - test
      - build:
          requires:
            - test
